import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import '@ant-design/v5-patch-for-react-19';
import { Toaster } from 'react-hot-toast';
import Provider from '@/store/store';

const roboto = Roboto({
    subsets: ['vietnamese'],
    weight: ['100', '300', '400', '700', '900'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${roboto.className} min-h-[100vh] roboto-regular`}
            >
                <Provider>{children}</Provider>
                <Toaster position="top-right" />
            </body>
        </html>
    );
}
